"""Analytical research components for the CQF AL project."""

from cqf_al.analysis.dependence_diagnostics import (
    DependenceDiagnosticBundle,
    DependenceDiagnosticError,
    build_daily_return_panel,
    build_dependence_diagnostics,
    build_pairwise_dependence_table,
    build_regime_dependence_tables,
    build_rolling_dependence_table,
    build_tail_dependence_table,
    build_volatility_regimes,
)
from cqf_al.analysis.eda_features import (
    DataQualityBundle,
    EdaFeatureBundle,
    EdaFeatureError,
    assert_analysis_ready,
    build_data_quality_tables,
    build_return_features,
    find_fatal_quality_failures,
    normalize_bars,
)
from cqf_al.analysis.event_bar_diagnostics import (
    EventBarDiagnosticBundle,
    EventBarDiagnosticError,
    build_conservation_table,
    build_event_bar_diagnostics,
    build_sampling_comparison,
    build_sampling_decision,
    build_time_bars_from_trades,
    calculate_event_thresholds,
    infer_time_rule,
    normalize_trade_sample,
)
from cqf_al.analysis.stylized_facts import (
    StylizedFactsBundle,
    StylizedFactsError,
    build_daily_acf_table,
    build_daily_ljung_box_table,
    build_distribution_tables,
    build_intraday_acf_table,
    build_stylized_facts,
)
from cqf_al.analysis.strategy_performance import (
    PerformanceMetrics,
    StrategyPerformanceError,
    build_performance_summary,
    build_wealth_index,
    calculate_performance_metrics,
)
from cqf_al.analysis.volatility_seasonality import (
    VolatilitySeasonalityBundle,
    VolatilitySeasonalityError,
    build_daily_volatility_table,
    build_intraday_seasonality_table,
    build_volatility_seasonality,
)


__all__ = [
    "DataQualityBundle",
    "DependenceDiagnosticBundle",
    "DependenceDiagnosticError",
    "EdaFeatureBundle",
    "EdaFeatureError",
    "EventBarDiagnosticBundle",
    "EventBarDiagnosticError",
    "PerformanceMetrics",
    "StrategyPerformanceError",
    "StylizedFactsBundle",
    "StylizedFactsError",
    "VolatilitySeasonalityBundle",
    "VolatilitySeasonalityError",
    "assert_analysis_ready",
    "build_conservation_table",
    "build_daily_acf_table",
    "build_daily_ljung_box_table",
    "build_daily_return_panel",
    "build_daily_volatility_table",
    "build_data_quality_tables",
    "build_dependence_diagnostics",
    "build_distribution_tables",
    "build_event_bar_diagnostics",
    "build_intraday_acf_table",
    "build_intraday_seasonality_table",
    "build_pairwise_dependence_table",
    "build_performance_summary",
    "build_regime_dependence_tables",
    "build_return_features",
    "build_rolling_dependence_table",
    "build_sampling_comparison",
    "build_sampling_decision",
    "build_stylized_facts",
    "build_tail_dependence_table",
    "build_time_bars_from_trades",
    "build_volatility_regimes",
    "build_volatility_seasonality",
    "build_wealth_index",
    "calculate_event_thresholds",
    "calculate_performance_metrics",
    "find_fatal_quality_failures",
    "infer_time_rule",
    "normalize_bars",
    "normalize_trade_sample",
]
